from typing import Optional, Union

import numpy as np

from ase.calculators.calculator import Calculator
from ase.data import covalent_radii
from ase.data.vdw_alvarez import vdw_radii

import torch
import warnings

def _resolve_torch_device(device_spec):
    """
    Resolve a torch device from a user spec.
    """
    if device_spec is None:
        d = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    else:
        try:
            d = torch.device(device_spec)
        except (TypeError, ValueError):
            warnings.warn(f"[dmf.torch] Invalid device spec '{device_spec}', falling back to CPU.")
            d = torch.device("cpu")
    if d.type == "cuda" and not torch.cuda.is_available():
        warnings.warn("[dmf.torch] CUDA requested but not available; falling back to CPU.")
        d = torch.device("cpu")
    return d


def _resolve_torch_dtype(dtype_spec):
    """
    Resolve a torch dtype from a user spec (float32/float64).
    """
    if dtype_spec is None:
        return torch.float64
    if isinstance(dtype_spec, torch.dtype):
        if dtype_spec in (torch.float32, torch.float64):
            return dtype_spec
        warnings.warn(f"[dmf.torch] Unsupported dtype '{dtype_spec}', falling back to float64.")
        return torch.float64
    if isinstance(dtype_spec, str):
        key = dtype_spec.strip().lower()
        if key in ("float32", "fp32", "single", "float"):
            return torch.float32
        if key in ("float64", "fp64", "double"):
            return torch.float64
        warnings.warn(f"[dmf.torch] Invalid dtype spec '{dtype_spec}', falling back to float64.")
        return torch.float64
    try:
        np_dtype = np.dtype(dtype_spec)
        if np_dtype.kind == "f" and np_dtype.itemsize == 4:
            return torch.float32
        if np_dtype.kind == "f" and np_dtype.itemsize == 8:
            return torch.float64
    except Exception:
        pass
    warnings.warn(f"[dmf.torch] Invalid dtype spec '{dtype_spec}', falling back to float64.")
    return torch.float64


@torch.no_grad()
def _calc_dist_mat(pos, *, device, dtype) -> torch.Tensor:
    pos_t = torch.as_tensor(pos, dtype=dtype, device=device)
    return torch.cdist(pos_t,pos_t)


class FB_ENM(Calculator):
    """
    ASE calculator for the Flat-bottom Elastic Network Model (FB-ENM).

    A lightweight structure-based potential for generating
    collision-free plausible paths used in combination with the
    direct MaxFlux method. Each pair interaction has a flat
    bottom defined by (d_min, d_max). This class implements the
    general pairwise model.

    This implementation follows the model introduced in:

        Koda & Saito, J. Chem. Theory Comput. 2024, 20, 7176–7187.

    See the original paper for theoretical details.

    Parameters
    ----------
    d_min, d_max : array-like, shape (N, N)
        Flat-bottom bounds for each pair distance.
    delta_min, delta_max : array-like, shape (N, N) or None
        Quadratic wall widths. If None, generated via ``delta_scale``.
    delta_scale : float
        Scale factor used when delta arrays are autogenerated.
    return_energy_mats : bool
        If True, include ``emat_rep`` and ``emat_att`` in results.
    device : str or torch.device, optional
        Torch device used only for the distance-matrix evaluation.
    dtype : str or torch.dtype, optional
        Torch floating-point dtype for internal calculations
        (``float32`` or ``float64``). Default: ``float64``.

    """

    implemented_properties = ['energy', 'forces']

    def __init__(
        self,
        d_min,
        d_max,
        delta_min: Optional[Union[np.ndarray, torch.Tensor]] = None,
        delta_max: Optional[Union[np.ndarray, torch.Tensor]] = None,
        delta_scale: float = 0.2,
        return_energy_mats: bool = False,
        device=None,
        dtype=None,
    ):
        super().__init__()

        self.device = _resolve_torch_device(device)
        self.torch_dtype = _resolve_torch_dtype(dtype)
        self.np_dtype = np.float64
        self._return_energy_mats = bool(return_energy_mats)
        self._d_min_t = None
        self._d_max_t = None
        self._delta_min_t = None
        self._delta_max_t = None

        def to_np(x) -> np.ndarray:
            if isinstance(x, torch.Tensor):
                return x.detach().cpu().numpy().astype(self.np_dtype, copy=False)
            return np.asarray(x, dtype=self.np_dtype)

        d_min_np = to_np(d_min).copy()
        d_max_np = to_np(d_max).copy()

        if delta_min is not None:
            delta_min_np = to_np(delta_min).copy()
        else:
            delta_min_np = (float(delta_scale) * d_min_np).copy()

        if delta_max is not None:
            delta_max_np = to_np(delta_max).copy()
        else:
            delta_max_np = (float(delta_scale) * d_max_np).copy()

        # Diagonal is unused; set to safe values to avoid divide-by-zero
        np.fill_diagonal(d_min_np, 0.0)
        np.fill_diagonal(d_max_np, 0.0)
        np.fill_diagonal(delta_min_np, 1.0)
        np.fill_diagonal(delta_max_np, 1.0)

        # Keep constants on CPU (NumPy) to minimize VRAM
        self.d_min = d_min_np
        self.d_max = d_max_np
        self.delta_min = delta_min_np
        self.delta_max = delta_max_np

    @torch.no_grad()
    def calculate(self, atoms, properties, system_changes):
        super().calculate(atoms, properties, system_changes)

        # 1) Distance matrix (Torch on self.device)
        pos = atoms.get_positions()
        pos_t = torch.as_tensor(pos, dtype=self.torch_dtype, device=self.device)
        d = torch.cdist(pos_t, pos_t)

        # Cache torch copies of constants on the target device/dtype
        if (self._d_min_t is None) or (self._d_min_t.device != self.device) or (self._d_min_t.dtype != self.torch_dtype):
            self._d_min_t = torch.as_tensor(self.d_min, dtype=self.torch_dtype, device=self.device)
        if (self._d_max_t is None) or (self._d_max_t.device != self.device) or (self._d_max_t.dtype != self.torch_dtype):
            self._d_max_t = torch.as_tensor(self.d_max, dtype=self.torch_dtype, device=self.device)
        if (self._delta_min_t is None) or (self._delta_min_t.device != self.device) or (self._delta_min_t.dtype != self.torch_dtype):
            self._delta_min_t = torch.as_tensor(self.delta_min, dtype=self.torch_dtype, device=self.device)
        if (self._delta_max_t is None) or (self._delta_max_t.device != self.device) or (self._delta_max_t.dtype != self.torch_dtype):
            self._delta_max_t = torch.as_tensor(self.delta_max, dtype=self.torch_dtype, device=self.device)

        # 2) Flat-bottom penalties (Torch on device)
        d_rep = torch.clamp(d - self._d_min_t, max=0.0)
        d_att = torch.clamp(d - self._d_max_t, min=0.0)

        inv_dmin2 = 1.0 / (self._delta_min_t * self._delta_min_t)
        inv_dmax2 = 1.0 / (self._delta_max_t * self._delta_max_t)

        if self._return_energy_mats:
            e_rep = (d_rep * d_rep) * inv_dmin2
            e_att = (d_att * d_att) * inv_dmax2
            # symmetric matrix -> half to count each pair once
            energy = 0.5 * torch.sum(e_rep + e_att)
        else:
            energy = 0.5 * torch.sum((d_rep * d_rep) * inv_dmin2 + (d_att * d_att) * inv_dmax2)

        # dE/dd  (up to a sign handled in force assembly)
        f1 = 2.0 * (d_rep * inv_dmin2 + d_att * inv_dmax2)

        # 3) Forces (Torch on device)
        # Avoid divide-by-zero on diagonal; diagonal term is zero anyway.
        d.fill_diagonal_(1.0)
        f1 = f1 / d
        # Ensure exact zeros on diagonal
        f1.fill_diagonal_(0.0)

        # Vectorized assembly:
        # F_i = sum_j (f1_ij * (r_j - r_i))
        s = torch.sum(f1, dim=1)  # (N,)
        forces = f1 @ pos_t - pos_t * s[:, None]  # (N,3)

        self.results = {
            'energy': float(energy.item()),
            'forces': forces.cpu().numpy(),
        }
        if self._return_energy_mats:
            # Keep energy matrices on device to avoid host transfer
            self.results['emat_rep'] = e_rep
            self.results['emat_att'] = e_att



class FB_ENM_Bonds(FB_ENM):
    """
    ASE calculator for bond-aware FB-ENM.

    Builds an FB-ENM automatically from multiple reference images.
    Bond lengths and bond angles preserved across all images are
    strongly constrained, while other distances receive weak bounds.

    Also supports optional planar constraints for π-like fragments.
    For details on how these constraints are defined, refer to:

        Koda & Saito, J. Chem. Theory Comput. 2024, 20, 7176–7187.

    Parameters
    ----------
    images : list of ase.Atoms
        Reference structures.
        Here, natoms = len(images[0]).
    addA : boolean ndarray of shape (natoms, natoms), optional
        Manually add strong constraints. Pairs marked True are added.
        Default: None.
    delA : boolean ndarray of shape (natoms, natoms), optional
        Manually remove strong constraints. Pairs marked True are removed.
        If both `addA` and `delA` are provided, `delA` takes precedence.
        Default: None.
    delta_scale : float, optional
        Scale for delta_min/max in the parent FB_ENM.
        Default: 0.2.
    bond_scale : float, optional
        Threshold for bond detection
        (bond is detected when d_ij < bond_scale × (r_cov[i] + r_cov[j])).
        Default: 1.25.
    fix_planes : bool, optional
        Whether to add additional constraints to preserve planar groups.
        Default: True.
    d_min_overwrite : float or ndarray of shape (natoms, natoms), optional
        Values used to overwrite selected entries of d_min.
        Only pairs where `A_overwrite` is True are replaced.
        Default: None.
    d_max_overwrite : float or ndarray of shape (natoms, natoms), optional
        Values used to overwrite selected entries of d_max.
        Only pairs where `A_overwrite` is True are replaced.
        Default: None.
    A_overwrite : boolean ndarray of shape (natoms, natoms), optional
        Boolean mask specifying which atom pairs should be overwritten.
        For any (i, j) where `A_overwrite[i, j] == True`, the following
        assignments are applied::

            d_min[A_overwrite] = d_min_overwrite[A_overwrite]
            d_max[A_overwrite] = d_max_overwrite[A_overwrite]

        Must be supplied when using either overwrite option.
        Default: None.
    device : str or torch.device, optional
        Torch device for internal tensors. If None, auto-select.
    dtype : str or torch.dtype, optional
        Torch floating-point dtype for internal calculations
        (``float32`` or ``float64``). Default: ``float64``.

    Notes
    -----
    - Weak constraints follow van der Waals and system-size bounds.

    """


    implemented_properties = ['energy', 'forces']

    def __init__(
        self,
        images: list,
        addA: Optional[np.ndarray] = None,
        delA: Optional[np.ndarray] = None,
        delta_scale: float = 0.2,
        bond_scale: float = 1.25,
        fix_planes: bool = True,
        d_min_overwrite: Optional[np.ndarray] = None,
        d_max_overwrite: Optional[np.ndarray] = None,
        A_overwrite: Optional[np.ndarray] = None,
        device=None,
        dtype=None,
    ):
        self.device = _resolve_torch_device(device)
        self.torch_dtype = _resolve_torch_dtype(dtype)
        self.np_dtype = np.float64
        _dev = self.device
        _tdt = self.torch_dtype

        numbers = images[0].arrays['numbers']
        r_cov_np = covalent_radii[numbers][:,None]+covalent_radii[numbers]
        r_vdw_np = vdw_radii[numbers][:,None]+vdw_radii[numbers]

        r_cov = torch.as_tensor(r_cov_np,dtype=_tdt,device=_dev)
        r_vdw = torch.as_tensor(r_vdw_np,dtype=_tdt,device=_dev)
        bond_scale_t = torch.tensor(float(bond_scale),dtype=_tdt,device=_dev)

        natoms = len(images[0])

        if fix_planes:
            addA_p = torch.zeros([natoms,natoms],dtype=torch.bool,device=_dev)
            planes = _get_planes(images, bond_scale=bond_scale, device=self.device, dtype=self.torch_dtype)
            for p in planes:
                idx = torch.as_tensor(p,device=_dev)
                addA_p[idx.unsqueeze(1),idx] = True
        else:
            addA_p = None

        addA_mask = torch.as_tensor(addA,dtype=torch.bool,device=_dev) if addA is not None else None
        delA_mask = torch.as_tensor(delA,dtype=torch.bool,device=_dev) if delA is not None else None

        d_min = torch.full([natoms,natoms],torch.inf,dtype=_tdt,device=_dev)
        d_max = torch.zeros([natoms,natoms],dtype=_tdt,device=_dev)

        with torch.no_grad():
            for image in images:
                d = _calc_dist_mat(image.get_positions(), device=self.device, dtype=self.torch_dtype)
                J = (d/r_cov)<bond_scale_t
                J_t = J.to(_tdt)
                A = (J_t@J_t)>0
                del J, J_t; torch.cuda.empty_cache()

                if fix_planes:
                    A = A|addA_p
                if addA_mask is not None:
                    A = A|addA_mask
                if delA_mask is not None:
                    A = A&(~delA_mask)

                cand_min = torch.where(A,d,torch.minimum(d,r_vdw))
                cand_max = torch.where(A,d,2.0*torch.amax(d))
                del d, A; torch.cuda.empty_cache()
                d_min = torch.minimum(d_min,cand_min)
                d_max = torch.maximum(d_max,cand_max)
                del cand_min, cand_max; torch.cuda.empty_cache()

            if (d_min_overwrite is not None) and (A_overwrite is not None):
                mask = torch.as_tensor(A_overwrite,dtype=torch.bool,device=_dev)
                d_min = torch.where(mask,torch.as_tensor(d_min_overwrite,dtype=_tdt,device=_dev),d_min)
            if (d_max_overwrite is not None) and (A_overwrite is not None):
                mask = torch.as_tensor(A_overwrite,dtype=torch.bool,device=_dev)
                d_max = torch.where(mask,torch.as_tensor(d_max_overwrite,dtype=_tdt,device=_dev),d_max)

        del numbers, r_cov_np, r_vdw_np, r_cov, r_vdw, bond_scale_t, natoms, addA_p, addA_mask, delA_mask; torch.cuda.empty_cache()
        super().__init__(d_min, d_max, delta_scale=delta_scale, device=device, dtype=self.torch_dtype)
        del d_min, d_max; torch.cuda.empty_cache()


class CFB_ENM(Calculator):
    """
    Correlated Flat-Bottom ENM (CFB-ENM).

    Extends FB-ENM by adding correlation terms between
    bond-breaking and bond-forming atom pairs. This enforces
    coordinated structural changes that FB-ENM cannot capture alone.

    The correlation model and selection of correlated quartets follow
    the formulation described in the companion paper:

        Koda & Saito, J. Chem. Theory Comput. 21, 3513-3522 (2025).

    See the original paper for the mathematical definitions.

    Parameters
    ----------
    images : list of ase.Atoms
        Reference structures.
        Here, natoms = len(images[0]).
    bond_scale : float
        Threshold to detect bonds from distances. Default: 1.25.
    d_corr0, d_corr1, d_corr2 : ndarray of shape (natoms, natoms) or None, optional
        Flat-bottom thresholds for the correlated pair-pair potential.
        See the original paper for their definitions.
        If None, they are generated by scaling the largest bond length.
        Default: None.
    corr0_scale : float
        Scaling factors used when d_corr arrays are not provided.
        See the original paper for their definitions.
        Default: 1.10.
    corr1_scale : float
        Scaling factors used when d_corr arrays are not provided.
        See the original paper for their definitions.
        Default: 1.50.
    corr2_scale : float
        Scaling factors used when d_corr arrays are not provided.
        See the original paper for their definitions.
        Default: 1.60.
    eps : float
        Small value added for numerical stability in the correlation term.
        See the original paper for their definitions.
        Default: 0.05.
    pivotal : bool
        If True, restrict correlation to pivot-based patterns.
        See the original paper for the definition of "pivot".
        Default: True.
    single : bool
        If True, require exactly one breaking and one forming bond at pivot.
        See the original paper for the definition of "single pivot".
        Default: True.
    remove_fourmembered : bool
        Exclude quasi-four-membered-ring patterns that lead to artifacts.
        See the original paper for the definition of "quasi-four-membered ring".
        Default: True.
    device : str or torch.device, optional
        Torch device for internal tensors. If None, auto-select.
    dtype : str or torch.dtype, optional
        Torch floating-point dtype for internal calculations
        (``float32`` or ``float64``). Default: ``float64``.

    Notes
    -----
    - CFB-ENM adds only correlation energy; FB-ENM must be used
      together if flat-bottom bond/angle constraints are required.
      That is, use CFB_ENM alongside FB_ENM_Bonds in a SumCalculator as::

            from ase.calculators.mixing import SumCalculator
            calc = SumCalculator([
                     FB_ENM_Bonds(...),
                     CFB_ENM(...)])
    """

    implemented_properties = ['energy', 'forces']

    def __init__(
        self,
        images,
        bond_scale: float = 1.25,
        d_corr0: Optional[np.ndarray] = None,
        corr0_scale: float = 1.10,
        d_corr1: Optional[np.ndarray] = None,
        corr1_scale: float = 1.50,
        d_corr2: Optional[np.ndarray] = None,
        corr2_scale: float = 1.60,
        eps: float = 0.05,
        pivotal: bool = True,
        single: bool = True,
        remove_fourmembered: bool = True,
        device=None,
        dtype=None,
    ):

        Calculator.__init__(self)
        self.device = _resolve_torch_device(device)
        self.torch_dtype = _resolve_torch_dtype(dtype)
        self.np_dtype = np.float64
        _dev = self.device
        _tdt = self.torch_dtype

        numbers = images[0].arrays['numbers']
        r_cov_np = covalent_radii[numbers][:,None]+covalent_radii[numbers]
        self.r_cov_t = torch.as_tensor(r_cov_np,dtype=_tdt,device=_dev)
        self.bond_scale_t = torch.tensor(float(bond_scale),dtype=_tdt,device=_dev)

        natoms = len(images[0])
        d_bonds = torch.zeros([len(images),natoms,natoms],dtype=_tdt,device=_dev)
        Js = []

        with torch.no_grad():
            for i,image in enumerate(images):
                d = _calc_dist_mat(image.get_positions(), device=self.device, dtype=self.torch_dtype)
                J = (d/self.r_cov_t)<self.bond_scale_t
                J.fill_diagonal_(False)
                Js.append(J)
                d_bonds[i] = torch.where(J,d,torch.zeros_like(d))
                del d; torch.cuda.empty_cache()

        self.d_bond = torch.max(d_bonds, dim=0).values.cpu().numpy()
        del d_bonds; torch.cuda.empty_cache()

        J_only_r = Js[0]&(~Js[-1])
        J_only_p = Js[-1]&(~Js[0])
        J_both = Js[0]&Js[-1]
        del Js; torch.cuda.empty_cache()

        self.quartets = self._get_quartets(
                            J_only_r,J_only_p,J_both,
                            pivotal=pivotal,single=single,
                            remove_fourmembered=remove_fourmembered)
        del J_only_r, J_only_p, J_both; torch.cuda.empty_cache()

        if d_corr0 is not None:
            self.d_corr0 = d_corr0
        else:
            self.d_corr0 = corr0_scale * self.d_bond

        if d_corr1 is not None:
            self.d_corr1 = d_corr1
        else:
            self.d_corr1 = corr1_scale * self.d_bond

        if d_corr2 is not None:
            self.d_corr2 = d_corr2
        else:
            self.d_corr2 = corr2_scale * self.d_bond

        self.eps = eps

        I = np.identity(natoms,dtype='bool')
        self.d_bond[I] = 0.0
        self.d_corr0[I] = 0.0
        self.d_corr1[I] = 0.0
        self.d_corr2[I] = 0.0

        self.d_corr0_t = torch.as_tensor(self.d_corr0,dtype=_tdt,device=_dev)
        self.d_corr1_t = torch.as_tensor(self.d_corr1,dtype=_tdt,device=_dev)
        self.d_corr2_t = torch.as_tensor(self.d_corr2,dtype=_tdt,device=_dev)
        if self.quartets:
            self.quartets_t = torch.as_tensor(self.quartets,dtype=torch.long,device=_dev)
        else:
            self.quartets_t = torch.zeros((0,4),dtype=torch.long,device=_dev)

    def _get_quartets(self,J_only_r,J_only_p,J_both,
            pivotal=True,single=True,remove_fourmembered=True):

        if isinstance(J_both,torch.Tensor):
            J_both_t = J_both.to(dtype=self.torch_dtype)
        else:
            J_both_t = torch.as_tensor(J_both, dtype=self.torch_dtype, device=self.device)
        J2 = (J_both_t @ J_both_t) > 0
        J2 = J2.cpu().numpy()
        del J_both_t; torch.cuda.empty_cache()

        J_only_r = J_only_r.cpu().numpy() if isinstance(J_only_r,torch.Tensor) else np.asarray(J_only_r,bool)
        J_only_p = J_only_p.cpu().numpy() if isinstance(J_only_p,torch.Tensor) else np.asarray(J_only_p,bool)
        J_both = J_both.cpu().numpy() if isinstance(J_both,torch.Tensor) else np.asarray(J_both,bool)

        if pivotal:
            quartets = []
            if single:
                pivots = np.where((np.sum(J_only_r,axis=1)==1)
                                        &(np.sum(J_only_p,axis=1)==1))[0]
            else:
                pivots = np.where(np.any(J_only_r,axis=1)
                                        &np.any(J_only_p,axis=1))[0]
            for i in pivots:
                only_r = np.where(J_only_r[i])[0]
                only_p = np.where(J_only_p[i])[0]
                for j in only_r:
                    for k in only_p:
                        if (not (remove_fourmembered and J2[j,k])):
                            quartets.append(list(map(int,[i,j,i,k])))

        else:
            pairs_only_r = []
            pairs_only_p = []
            for i in range(len(J_only_r)):
                for j in range(i):
                    if J_only_r[i,j]:
                        pairs_only_r.append([i,j])
                    if J_only_p[i,j]:
                        pairs_only_p.append([i,j])

            quartets = []
            for pr in pairs_only_r:
                for pp in pairs_only_p:
                    q = pr+pp

                    if remove_fourmembered:
                        uniq_idxs = [q[i] for i in range(4) if q.count(q[i])==1]

                        if len(uniq_idxs)==4:
                            is_fourmembered = \
                                (J_both[q[0],q[2]] and J_both[q[1],q[3]]) \
                                or (J_both[q[0],q[3]] and J_both[q[1],q[2]])
                        else:
                            is_fourmembered = J2[uniq_idxs[0],uniq_idxs[1]]

                        if is_fourmembered:
                            continue

                    quartets.append(q)

        return quartets

    @torch.no_grad()
    def calculate(self, atoms, properties, system_changes):
        Calculator.calculate(self, atoms, properties, system_changes)

        r = atoms.get_positions()

        natoms = len(atoms)
        if self.quartets_t.numel()==0:
            self.results = {'energy': 0.0,
                            'forces': np.zeros([natoms,3], dtype=self.np_dtype)}
            del natoms, r; torch.cuda.empty_cache()
            return

        pos = torch.as_tensor(r, dtype=self.torch_dtype, device=self.device)
        q = self.quartets_t
        i = q[:,0]; j = q[:,1]; k = q[:,2]; l = q[:,3]

        diff_ij = pos[i]-pos[j]
        diff_kl = pos[k]-pos[l]
        d_ij = torch.linalg.norm(diff_ij,dim=1)
        d_kl = torch.linalg.norm(diff_kl,dim=1)

        d00_ij = self.d_corr0_t[i,j]; d00_kl = self.d_corr0_t[k,l]
        d10_ij = self.d_corr1_t[i,j]-d00_ij
        d10_kl = self.d_corr1_t[k,l]-d00_kl
        d20_ij = self.d_corr2_t[i,j]-d00_ij
        d20_kl = self.d_corr2_t[k,l]-d00_kl

        dd0_ij = d_ij-d00_ij
        dd0_kl = d_kl-d00_kl

        pp = dd0_ij*dd0_kl-d10_ij*d10_kl
        ok = (dd0_ij>0.0)&(dd0_kl>0.0)&(pp>0.0)
        if not torch.any(ok):
            self.results = {'energy': 0.0,
                            'forces': np.zeros([natoms,3], dtype=self.np_dtype)}
            del natoms, pos, q, i, j, k, l, diff_ij, diff_kl, d_ij, d_kl, d00_ij, d00_kl, d10_ij, d10_kl, d20_ij, d20_kl, dd0_ij, dd0_kl, pp, ok; torch.cuda.empty_cache()
            return

        i = i[ok]; j = j[ok]; k = k[ok]; l = l[ok]
        diff_ij = diff_ij[ok]; diff_kl = diff_kl[ok]
        d_ij = d_ij[ok]; d_kl = d_kl[ok]
        dd0_ij = dd0_ij[ok]; dd0_kl = dd0_kl[ok]
        d10_ij = d10_ij[ok]; d10_kl = d10_kl[ok]
        d20_ij = d20_ij[ok]; d20_kl = d20_kl[ok]
        pp = pp[ok]

        dnm = d20_ij*d20_kl-d10_ij*d10_kl
        pp = pp/dnm
        eps = float(self.eps)
        sqrt_pp2 = torch.sqrt(pp*pp+eps*eps)
        alpha = pp/sqrt_pp2
        energy = torch.sum(sqrt_pp2-eps).item()

        v1 = (dd0_kl/d_ij).unsqueeze(1)*(diff_ij/dnm.unsqueeze(1))
        v2 = (dd0_ij/d_kl).unsqueeze(1)*(diff_kl/dnm.unsqueeze(1))

        forces = torch.zeros([natoms,3], dtype=self.torch_dtype, device=self.device)
        forces.index_add_(0,i,-alpha.unsqueeze(1)*v1)
        forces.index_add_(0,j, alpha.unsqueeze(1)*v1)
        forces.index_add_(0,k,-alpha.unsqueeze(1)*v2)
        forces.index_add_(0,l, alpha.unsqueeze(1)*v2)

        self.results = {'energy': float(energy),
                        'forces': forces.cpu().numpy()}
        del natoms, pos, q, i, j, k, l, diff_ij, diff_kl, d_ij, d_kl, d00_ij, d00_kl, d10_ij, d10_kl, d20_ij, d20_kl, dd0_ij, dd0_kl, pp, dnm, eps, sqrt_pp2, alpha, v1, v2, forces; torch.cuda.empty_cache()


def _get_planes(images, bond_scale=1.25, tol_rmsd=0.05, tol_ang=10.0, *, device=None, dtype=None):

    def rmsd(pos,c4):
        x = pos[c4]
        cent = torch.mean(x,dim=0,keepdim=True)
        _, _, vh = torch.linalg.svd(x-cent,full_matrices=False)
        v = vh[-1,:]
        d = torch.matmul(x-cent,v)
        return torch.sqrt(torch.mean(d*d)).item()

    def is_not_linear(atoms,c4):
        ang0 = atoms.get_angle(*c4[0:3])
        ang1 = atoms.get_angle(*c4[1:4])
        return 180.0-ang0>tol_ang and 180.0-ang1>tol_ang

    def is_cis(atoms,c4):
        dh = atoms.get_dihedral(*c4)
        return np.cos(np.pi/180*dh)>=0.0

    def is_trans(atoms,c4):
        dh = atoms.get_dihedral(*c4)
        return np.cos(np.pi/180*dh)<0.0

    def is_connected(nghs,c4):
        ret = c4[0] in nghs[c4[1]]
        ret = ret and c4[1] in nghs[c4[2]]
        ret = ret and c4[2] in nghs[c4[3]]
        return ret

    def is_connected_center(nghs,c4):
        ret = c4[0] in nghs[c4[1]]
        ret = ret and c4[0] in nghs[c4[2]]
        ret = ret and c4[0] in nghs[c4[3]]
        return ret

    device = _resolve_torch_device(device)
    torch_dtype = _resolve_torch_dtype(dtype)
    bond_scale_t = torch.tensor(float(bond_scale), dtype=torch_dtype, device=device)

    for iimg, atoms in enumerate(images):

        pos = torch.as_tensor(atoms.get_positions(), dtype=torch_dtype, device=device)
        cov_radii = covalent_radii[atoms.arrays['numbers']]
        r_cov = torch.as_tensor(cov_radii, dtype=torch_dtype, device=device)
        r_cov = r_cov + r_cov.unsqueeze(1)
        d = _calc_dist_mat(pos, device=device, dtype=torch_dtype)
        A = (d/r_cov)<bond_scale_t
        A.fill_diagonal_(False)
        nghs = []
        for row in A:
            nghs.append(row.nonzero(as_tuple=False).squeeze(1).cpu().tolist())

        if iimg==0:
            path = []
            c4s = []
            def next(i):
                if i not in path:
                    path.append(i)
                    if len(path)==4:
                        if path[0]<path[3]:
                            c4s.append(list(path))
                    else:
                        for j in nghs[i]:
                            next(j)
                    path.pop()

            for i in range(len(atoms)):
                next(i)

            c4s_center = []
            for i0 in range(len(atoms)):
                nngh = len(nghs[i0])
                if nngh>=3:
                    for i1 in range(nngh):
                        for i2 in range(i1+1,nngh):
                            for i3 in range(i2+1,nngh):
                                c4s_center.append([i0,
                                                   nghs[i0][i1],
                                                   nghs[i0][i2],
                                                   nghs[i0][i3]])

            pels_cis = [c4 for c4 in c4s if (rmsd(pos,c4)<tol_rmsd
                                             and is_not_linear(atoms,c4)
                                             and is_cis(atoms,c4))]
            pels_trans = [c4 for c4 in c4s if (rmsd(pos,c4)<tol_rmsd
                                             and is_not_linear(atoms,c4)
                                             and is_trans(atoms,c4))]
            pels_center = [c4 for c4 in c4s_center if (rmsd(pos,c4)<tol_rmsd)]
            del pos, cov_radii, r_cov, d, A, nghs; torch.cuda.empty_cache()

        else:
            pels_cis = [c4 for c4 in pels_cis
                           if (rmsd(pos,c4)<tol_rmsd
                               and is_not_linear(atoms,c4)
                               and is_cis(atoms,c4)
                               and is_connected(nghs,c4))]
            pels_trans = [c4 for c4 in pels_trans
                             if (rmsd(pos,c4)<tol_rmsd
                                 and is_not_linear(atoms,c4)
                                 and is_trans(atoms,c4)
                                 and is_connected(nghs,c4))]
            pels_center = [c4 for c4 in pels_center
                              if (rmsd(pos,c4)<tol_rmsd
                                  and is_connected_center(nghs,c4))]
            del pos, cov_radii, r_cov, d, A, nghs; torch.cuda.empty_cache()

    pels = [set(pel) for pel in pels_cis+pels_trans+pels_center]


    planes = []
    pels_del = []

    while len(pels)>0:
        if len(pels_del)==0:
            planes.append(pels[-1])
            pels.pop()

        pels_del = [pel for pel in pels if len(planes[-1]&pel)>=3]
        pels = [pel for pel in pels if len(planes[-1]&pel)<3]
        planes[-1] = planes[-1].union(*pels_del)

    return [sorted(p) for p in planes]
