name: Tests (conda)
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - uses: actions/checkout@v5

      - name: Setup Micromamba
        uses: mamba-org/setup-micromamba@v3
        with:
          micromamba-version: 'latest'
          environment-name: pydmf
          create-args: >-
            python=${{ matrix.python-version }}
          cache-environment: true

      - name: Install dependencies
        run: |
          micromamba install -y -c conda-forge ase cyipopt pytest

      - name: Install PyDMF
        run: |
          pip install torch --index-url https://download.pytorch.org/whl/cpu
          pip install -e .[torch]

      - name: Run tests
        run: |
          pytest -v
